/**
 * Built-in theme presets — matches `nil_sb_builtin_presets()` (PHP).
 * Each preset is a complete token bundle that can be applied to a site.
 * Users can save custom presets to public.user_theme_presets.
 */

export interface ThemeTokens {
  mode: 'dark' | 'light'
  primary: string
  secondary: string
  accent: string
  bg_color: string
  card_bg: string
  border_color: string
  text_color: string
  heading_color: string
  muted_color: string
  nav_bg: string
  nav_text: string
  font_heading: string
  font_body: string
  heading_weight: number
  body_weight: number
  base_font_size: number
  nav_font_size: number
  button_style: 'filled' | 'outline'
  button_radius: number
  card_radius: number
  card_shadow: 'none' | 'sm' | 'md' | 'lg'
  nav_sticky: boolean
  nav_transparent: boolean
  nav_hover_style: 'background' | 'underline' | 'glow' | 'color-only'
  hero_height: string
  hero_overlay_color: string
  hero_overlay_opacity: number
  section_padding: string
  content_width: string
  logo_url?: string
  logo_height?: number
  logo_height_mobile?: number
  custom_css?: string
}

export interface ThemePreset {
  id: string
  name: string
  description: string
  tokens: ThemeTokens
}

const baseDark: Partial<ThemeTokens> = {
  mode: 'dark',
  heading_weight: 900,
  body_weight: 400,
  base_font_size: 16,
  nav_font_size: 13,
  button_style: 'filled',
  button_radius: 8,
  card_radius: 12,
  card_shadow: 'md',
  nav_sticky: true,
  nav_transparent: false,
  nav_hover_style: 'background',
  hero_height: '70vh',
  hero_overlay_color: '#000000',
  hero_overlay_opacity: 0.4,
  section_padding: '4rem',
  content_width: '1200px',
}

const baseLight: Partial<ThemeTokens> = {
  ...baseDark,
  mode: 'light',
}

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: 'midnight-pro',
    name: 'Midnight Pro',
    description: 'Cool dark theme with electric blue accents.',
    tokens: {
      ...baseDark,
      primary: '#3b82f6',
      secondary: '#0a0a0a',
      accent: '#60a5fa',
      bg_color: '#0a0a0a',
      card_bg: '#161616',
      border_color: '#262626',
      text_color: '#e5e5e5',
      heading_color: '#ffffff',
      muted_color: '#737373',
      nav_bg: '#0a0a0a',
      nav_text: '#ffffff',
      font_heading: 'Inter',
      font_body: 'Inter',
    } as ThemeTokens,
  },
  {
    id: 'scarlet-bold',
    name: 'Scarlet Bold',
    description: 'High-impact red on near-black.',
    tokens: {
      ...baseDark,
      primary: '#dc2626',
      secondary: '#0a0a0a',
      accent: '#fbbf24',
      bg_color: '#0a0a0a',
      card_bg: '#171717',
      border_color: '#262626',
      text_color: '#f5f5f5',
      heading_color: '#ffffff',
      muted_color: '#a3a3a3',
      nav_bg: '#0a0a0a',
      nav_text: '#ffffff',
      font_heading: 'Bebas Neue',
      font_body: 'Inter',
    } as ThemeTokens,
  },
  {
    id: 'neon-edge',
    name: 'Neon Edge',
    description: 'Cyber-night with magenta glow.',
    tokens: {
      ...baseDark,
      primary: '#d946ef',
      secondary: '#020617',
      accent: '#22d3ee',
      bg_color: '#020617',
      card_bg: '#0f172a',
      border_color: '#1e293b',
      text_color: '#e2e8f0',
      heading_color: '#f8fafc',
      muted_color: '#64748b',
      nav_bg: '#020617',
      nav_text: '#f8fafc',
      font_heading: 'Oswald',
      font_body: 'Inter',
      nav_hover_style: 'glow',
    } as ThemeTokens,
  },
  {
    id: 'forest-calm',
    name: 'Forest Calm',
    description: 'Deep green with warm accents.',
    tokens: {
      ...baseDark,
      primary: '#22c55e',
      secondary: '#052e16',
      accent: '#fbbf24',
      bg_color: '#052e16',
      card_bg: '#14532d',
      border_color: '#166534',
      text_color: '#d1fae5',
      heading_color: '#ffffff',
      muted_color: '#86efac',
      nav_bg: '#052e16',
      nav_text: '#ffffff',
      font_heading: 'Playfair Display',
      font_body: 'Lora',
    } as ThemeTokens,
  },
  {
    id: 'royal-gold',
    name: 'Royal Gold',
    description: 'Black + gold luxury.',
    tokens: {
      ...baseDark,
      primary: '#C8A84E',
      secondary: '#0a0a0a',
      accent: '#facc15',
      bg_color: '#0a0a0a',
      card_bg: '#171717',
      border_color: '#3f3f46',
      text_color: '#f5f5f4',
      heading_color: '#facc15',
      muted_color: '#a8a29e',
      nav_bg: '#0a0a0a',
      nav_text: '#facc15',
      font_heading: 'Playfair Display',
      font_body: 'Lora',
    } as ThemeTokens,
  },
  {
    id: 'stealth-ops',
    name: 'Stealth Ops',
    description: 'Tactical grey + safety orange.',
    tokens: {
      ...baseDark,
      primary: '#f97316',
      secondary: '#171717',
      accent: '#facc15',
      bg_color: '#0a0a0a',
      card_bg: '#171717',
      border_color: '#404040',
      text_color: '#e5e5e5',
      heading_color: '#ffffff',
      muted_color: '#a3a3a3',
      nav_bg: '#0a0a0a',
      nav_text: '#f97316',
      font_heading: 'Oswald',
      font_body: 'Roboto',
    } as ThemeTokens,
  },
  {
    id: 'electric-violet',
    name: 'Electric Violet',
    description: 'Bold violet with cool blue accents.',
    tokens: {
      ...baseDark,
      primary: '#8b5cf6',
      secondary: '#1e1b4b',
      accent: '#22d3ee',
      bg_color: '#0f0a25',
      card_bg: '#1e1b4b',
      border_color: '#312e81',
      text_color: '#e9d5ff',
      heading_color: '#ffffff',
      muted_color: '#a78bfa',
      nav_bg: '#0f0a25',
      nav_text: '#ffffff',
      font_heading: 'Montserrat',
      font_body: 'Poppins',
    } as ThemeTokens,
  },
  {
    id: 'fire-ice',
    name: 'Fire & Ice',
    description: 'Hot pink + glacial blue contrast.',
    tokens: {
      ...baseDark,
      primary: '#ec4899',
      secondary: '#1e293b',
      accent: '#0ea5e9',
      bg_color: '#0c1428',
      card_bg: '#1e293b',
      border_color: '#334155',
      text_color: '#f1f5f9',
      heading_color: '#ffffff',
      muted_color: '#94a3b8',
      nav_bg: '#0c1428',
      nav_text: '#ffffff',
      font_heading: 'Raleway',
      font_body: 'Inter',
    } as ThemeTokens,
  },
  {
    id: 'dark-carbon',
    name: 'Dark Carbon',
    description: 'Minimalist matte black with white type.',
    tokens: {
      ...baseDark,
      primary: '#ffffff',
      secondary: '#000000',
      accent: '#737373',
      bg_color: '#000000',
      card_bg: '#0a0a0a',
      border_color: '#262626',
      text_color: '#e5e5e5',
      heading_color: '#ffffff',
      muted_color: '#737373',
      nav_bg: '#000000',
      nav_text: '#ffffff',
      font_heading: 'DM Sans',
      font_body: 'Inter',
      button_style: 'outline',
    } as ThemeTokens,
  },
  {
    id: 'ocean-depth',
    name: 'Ocean Depth',
    description: 'Cool teal + deep navy.',
    tokens: {
      ...baseDark,
      primary: '#14b8a6',
      secondary: '#0c4a6e',
      accent: '#67e8f9',
      bg_color: '#082f49',
      card_bg: '#0c4a6e',
      border_color: '#075985',
      text_color: '#cffafe',
      heading_color: '#ffffff',
      muted_color: '#7dd3fc',
      nav_bg: '#082f49',
      nav_text: '#ffffff',
      font_heading: 'Montserrat',
      font_body: 'Open Sans',
    } as ThemeTokens,
  },
  {
    id: 'matte-black',
    name: 'Matte Black',
    description: 'Pure matte with gold accent.',
    tokens: {
      ...baseDark,
      primary: '#fbbf24',
      secondary: '#0a0a0a',
      accent: '#d97706',
      bg_color: '#0a0a0a',
      card_bg: '#171717',
      border_color: '#262626',
      text_color: '#e5e5e5',
      heading_color: '#ffffff',
      muted_color: '#737373',
      nav_bg: '#0a0a0a',
      nav_text: '#ffffff',
      font_heading: 'Bebas Neue',
      font_body: 'Inter',
    } as ThemeTokens,
  },
  {
    id: 'sunset-blaze',
    name: 'Sunset Blaze',
    description: 'Warm orange/pink gradient feel.',
    tokens: {
      ...baseDark,
      primary: '#f97316',
      secondary: '#7f1d1d',
      accent: '#fbbf24',
      bg_color: '#1a0a0a',
      card_bg: '#3f1d1d',
      border_color: '#7f1d1d',
      text_color: '#fed7aa',
      heading_color: '#ffffff',
      muted_color: '#fbbf24',
      nav_bg: '#1a0a0a',
      nav_text: '#ffffff',
      font_heading: 'Oswald',
      font_body: 'Poppins',
    } as ThemeTokens,
  },
  {
    id: 'midnight-emerald',
    name: 'Midnight Emerald',
    description: 'Deep night with emerald glow.',
    tokens: {
      ...baseDark,
      primary: '#10b981',
      secondary: '#020617',
      accent: '#6ee7b7',
      bg_color: '#020617',
      card_bg: '#0f172a',
      border_color: '#1e293b',
      text_color: '#d1fae5',
      heading_color: '#ffffff',
      muted_color: '#64748b',
      nav_bg: '#020617',
      nav_text: '#10b981',
      font_heading: 'Montserrat',
      font_body: 'Inter',
    } as ThemeTokens,
  },
  {
    id: 'chrome-rush',
    name: 'Chrome Rush',
    description: 'Polished steel with chrome highlights.',
    tokens: {
      ...baseDark,
      primary: '#94a3b8',
      secondary: '#1e293b',
      accent: '#ffffff',
      bg_color: '#0f172a',
      card_bg: '#1e293b',
      border_color: '#475569',
      text_color: '#e2e8f0',
      heading_color: '#ffffff',
      muted_color: '#94a3b8',
      nav_bg: '#0f172a',
      nav_text: '#e2e8f0',
      font_heading: 'Bebas Neue',
      font_body: 'Roboto',
    } as ThemeTokens,
  },
  {
    id: 'blood-orange',
    name: 'Blood Orange',
    description: 'Citrus fire on charcoal.',
    tokens: {
      ...baseDark,
      primary: '#ea580c',
      secondary: '#1c1917',
      accent: '#fde047',
      bg_color: '#1c1917',
      card_bg: '#292524',
      border_color: '#44403c',
      text_color: '#fafaf9',
      heading_color: '#ffffff',
      muted_color: '#a8a29e',
      nav_bg: '#1c1917',
      nav_text: '#ea580c',
      font_heading: 'Raleway',
      font_body: 'Inter',
    } as ThemeTokens,
  },
  {
    id: 'arctic-night',
    name: 'Arctic Night',
    description: 'Crisp icy blue tones.',
    tokens: {
      ...baseDark,
      primary: '#38bdf8',
      secondary: '#0c4a6e',
      accent: '#7dd3fc',
      bg_color: '#082f49',
      card_bg: '#0c4a6e',
      border_color: '#075985',
      text_color: '#e0f2fe',
      heading_color: '#ffffff',
      muted_color: '#7dd3fc',
      nav_bg: '#082f49',
      nav_text: '#ffffff',
      font_heading: 'DM Sans',
      font_body: 'Inter',
    } as ThemeTokens,
  },
  {
    id: 'rose-gold',
    name: 'Rose Gold',
    description: 'Elegant rose with cream.',
    tokens: {
      ...baseLight,
      primary: '#e11d48',
      secondary: '#fff1f2',
      accent: '#fbbf24',
      bg_color: '#fff1f2',
      card_bg: '#ffe4e6',
      border_color: '#fecdd3',
      text_color: '#451a03',
      heading_color: '#9f1239',
      muted_color: '#9a8e8a',
      nav_bg: '#fff1f2',
      nav_text: '#9f1239',
      font_heading: 'Playfair Display',
      font_body: 'Lora',
    } as ThemeTokens,
  },
  {
    id: 'clean-light',
    name: 'Clean Light',
    description: 'Pristine light theme with subtle navy.',
    tokens: {
      ...baseLight,
      primary: '#1e3a8a',
      secondary: '#f8fafc',
      accent: '#3b82f6',
      bg_color: '#ffffff',
      card_bg: '#f8fafc',
      border_color: '#e2e8f0',
      text_color: '#1e293b',
      heading_color: '#0f172a',
      muted_color: '#64748b',
      nav_bg: '#ffffff',
      nav_text: '#0f172a',
      font_heading: 'Inter',
      font_body: 'Inter',
    } as ThemeTokens,
  },
  {
    id: 'fresh-mint',
    name: 'Fresh Mint',
    description: 'Light mint green with white.',
    tokens: {
      ...baseLight,
      primary: '#059669',
      secondary: '#ecfdf5',
      accent: '#34d399',
      bg_color: '#ffffff',
      card_bg: '#f0fdf4',
      border_color: '#bbf7d0',
      text_color: '#14532d',
      heading_color: '#064e3b',
      muted_color: '#6b7280',
      nav_bg: '#ffffff',
      nav_text: '#064e3b',
      font_heading: 'Nunito',
      font_body: 'Nunito',
    } as ThemeTokens,
  },
  {
    id: 'paper-minimal',
    name: 'Paper Minimal',
    description: 'Minimalist newsprint look.',
    tokens: {
      ...baseLight,
      primary: '#000000',
      secondary: '#fafaf9',
      accent: '#737373',
      bg_color: '#fafaf9',
      card_bg: '#ffffff',
      border_color: '#e7e5e4',
      text_color: '#1c1917',
      heading_color: '#000000',
      muted_color: '#78716c',
      nav_bg: '#fafaf9',
      nav_text: '#000000',
      font_heading: 'Playfair Display',
      font_body: 'Lora',
      button_style: 'outline',
      card_shadow: 'none',
    } as ThemeTokens,
  },
  {
    id: 'sky-blue',
    name: 'Sky Blue',
    description: 'Airy blue + white.',
    tokens: {
      ...baseLight,
      primary: '#0284c7',
      secondary: '#e0f2fe',
      accent: '#0ea5e9',
      bg_color: '#ffffff',
      card_bg: '#f0f9ff',
      border_color: '#bae6fd',
      text_color: '#0c4a6e',
      heading_color: '#082f49',
      muted_color: '#0369a1',
      nav_bg: '#ffffff',
      nav_text: '#082f49',
      font_heading: 'DM Sans',
      font_body: 'Inter',
    } as ThemeTokens,
  },
  {
    id: 'warm-cream',
    name: 'Warm Cream',
    description: 'Beige + burnt orange.',
    tokens: {
      ...baseLight,
      primary: '#c2410c',
      secondary: '#fefce8',
      accent: '#a16207',
      bg_color: '#fefce8',
      card_bg: '#fffbeb',
      border_color: '#fef08a',
      text_color: '#451a03',
      heading_color: '#7c2d12',
      muted_color: '#a16207',
      nav_bg: '#fefce8',
      nav_text: '#7c2d12',
      font_heading: 'Playfair Display',
      font_body: 'Lora',
    } as ThemeTokens,
  },
  {
    id: 'slate-pro',
    name: 'Slate Pro',
    description: 'Pro corporate slate + accent blue.',
    tokens: {
      ...baseDark,
      primary: '#3b82f6',
      secondary: '#1e293b',
      accent: '#60a5fa',
      bg_color: '#0f172a',
      card_bg: '#1e293b',
      border_color: '#334155',
      text_color: '#cbd5e1',
      heading_color: '#f1f5f9',
      muted_color: '#94a3b8',
      nav_bg: '#0f172a',
      nav_text: '#f1f5f9',
      font_heading: 'Inter',
      font_body: 'Inter',
    } as ThemeTokens,
  },
  {
    id: 'coral-breeze',
    name: 'Coral Breeze',
    description: 'Soft coral with seafoam.',
    tokens: {
      ...baseLight,
      primary: '#fb7185',
      secondary: '#ecfeff',
      accent: '#22d3ee',
      bg_color: '#ffffff',
      card_bg: '#fdf2f8',
      border_color: '#fce7f3',
      text_color: '#581c87',
      heading_color: '#831843',
      muted_color: '#a16207',
      nav_bg: '#ffffff',
      nav_text: '#831843',
      font_heading: 'Raleway',
      font_body: 'Inter',
    } as ThemeTokens,
  },
]

export const THEME_PRESETS_BY_ID = Object.fromEntries(
  THEME_PRESETS.map((p) => [p.id, p])
) as Record<string, ThemePreset>

export function defaultTokens(): ThemeTokens {
  return THEME_PRESETS_BY_ID['royal-gold']!.tokens
}

export const HEADING_FONTS = [
  'DM Sans',
  'Inter',
  'Montserrat',
  'Playfair Display',
  'Oswald',
  'Raleway',
  'Poppins',
  'Roboto Slab',
  'Lora',
  'Bebas Neue',
]

export const BODY_FONTS = [
  'Inter',
  'Open Sans',
  'Lato',
  'Roboto',
  'Source Sans Pro',
  'Nunito',
  'Work Sans',
  'Karla',
  'IBM Plex Sans',
  'Lora',
]
