/**
 * Generates a per-app Expo (React Native) project ZIP.
 *
 * The output is a minimal but real Expo template the talent (or their
 * dev) can `npx expo install` against and ship. Everything dynamic
 * (app name, package id, screens, theme colors) is templated in from
 * the talent_apps row.
 */
import JSZip from 'jszip'
import { screenPattern, type ScreenPattern } from '@/lib/app-screens'

export interface ExpoBuildInput {
  name: string
  slug: string
  tagline?: string | null
  description?: string | null
  package_id: string
  primary_color: string
  secondary_color: string
  theme_mode: 'dark' | 'light'
  icon_url?: string | null
  splash_url?: string | null
  privacy_policy_url?: string | null
  contact_email?: string | null
  app_id?: string | null
  edgezone_api_url?: string | null
  push_enabled?: boolean
  iap_enabled?: boolean
  iap_products?: Array<{
    product_id: string
    display_name: string
    price_usd: number
    kind: string
    apple_product_id?: string | null
    google_product_id?: string | null
  }>
  screens: Array<{
    id: string
    title: string
    icon?: string
    type: string
    content?: Record<string, unknown>
  }>
}

export async function buildExpoZip(
  input: ExpoBuildInput
): Promise<{ zipBuffer: Buffer; filename: string }> {
  const zip = new JSZip()
  const safeSlug = input.slug.replace(/[^a-z0-9-]/gi, '-')

  // ── package.json ──────────────────────────────────────────────────
  zip.file(
    'package.json',
    JSON.stringify(
      {
        name: safeSlug,
        version: '1.0.0',
        main: 'index.js',
        scripts: {
          start: 'expo start',
          android: 'expo run:android',
          ios: 'expo run:ios',
        },
        dependencies: {
          expo: '~51.0.0',
          'expo-status-bar': '~1.12.0',
          react: '18.2.0',
          'react-native': '0.74.5',
          '@react-navigation/native': '^6.1.18',
          '@react-navigation/bottom-tabs': '^6.6.0',
          '@expo/vector-icons': '^14.0.0',
          'react-native-safe-area-context': '4.10.5',
          'react-native-screens': '3.31.1',
          'react-native-webview': '13.8.6',
          ...(input.push_enabled
            ? {
                'expo-notifications': '~0.28.0',
                'expo-device': '~6.0.0',
                'expo-constants': '~16.0.0',
              }
            : {}),
          ...(input.iap_enabled ? { 'react-native-iap': '^12.15.0' } : {}),
        },
      },
      null,
      2
    )
  )

  // ── app.json ──────────────────────────────────────────────────────
  zip.file(
    'app.json',
    JSON.stringify(
      {
        expo: {
          name: input.name,
          slug: safeSlug,
          version: '1.0.0',
          orientation: 'portrait',
          icon: input.icon_url ? './assets/icon.png' : './assets/icon.png',
          userInterfaceStyle: input.theme_mode === 'dark' ? 'dark' : 'light',
          splash: {
            image: './assets/splash.png',
            resizeMode: 'contain',
            backgroundColor: input.secondary_color,
          },
          assetBundlePatterns: ['**/*'],
          ios: {
            supportsTablet: true,
            bundleIdentifier: input.package_id,
            buildNumber: '1',
          },
          android: {
            package: input.package_id,
            versionCode: 1,
            adaptiveIcon: {
              foregroundImage: './assets/adaptive-icon.png',
              backgroundColor: input.primary_color,
            },
          },
          web: { favicon: './assets/icon.png' },
          ...(input.push_enabled
            ? {
                plugins: [
                  [
                    'expo-notifications',
                    {
                      icon: './assets/icon.png',
                      color: input.primary_color,
                    },
                  ],
                ],
                notification: {
                  iosDisplayInForeground: true,
                },
              }
            : {}),
        },
      },
      null,
      2
    )
  )

  // ── src/config.js (Edge Zone API binding) ─────────────────────────
  zip.file(
    'src/config.js',
    `// Auto-generated by Edge Zone. Don't edit unless you're moving providers.
export const EDGEZONE_APP_ID = ${JSON.stringify(input.app_id ?? '')};
export const EDGEZONE_API_URL = ${JSON.stringify(input.edgezone_api_url ?? 'https://theedgezone.com')};
export const PUSH_ENABLED = ${input.push_enabled ? 'true' : 'false'};
export const IAP_ENABLED = ${input.iap_enabled ? 'true' : 'false'};
export const IAP_PRODUCTS = ${JSON.stringify(input.iap_products ?? [], null, 2)};
`
  )

  if (input.push_enabled) {
    zip.file('src/push.js', renderPushModule())
  }
  if (input.iap_enabled) {
    zip.file('src/iap.js', renderIapModule())
  }

  // ── babel.config.js ────────────────────────────────────────────────
  zip.file(
    'babel.config.js',
    `module.exports = function (api) {
  api.cache(true)
  return {
    presets: ['babel-preset-expo'],
  }
}
`
  )

  // ── index.js ──────────────────────────────────────────────────────
  zip.file('index.js', `import { registerRootComponent } from 'expo'\nimport App from './App'\nregisterRootComponent(App)\n`)

  // ── App.js (entry) ────────────────────────────────────────────────
  zip.file(
    'App.js',
    renderAppJs(input)
  )

  // App.js is a thin native shell that loads the live Edge Zone app (PWA) in a
  // WebView — edits in the dashboard appear instantly, no rebuild. These
  // per-screen native files are kept as an optional scaffold if a dev later
  // wants to hand-build native screens; the shipped app doesn't import them.
  const srcFolder = zip.folder('src')!
  const screensFolder = srcFolder.folder('screens')!
  for (const screen of input.screens) {
    screensFolder.file(`${pascal(screen.id)}Screen.js`, renderScreenJs(screen, input))
  }

  // ── README ───────────────────────────────────────────────────────
  zip.file(
    'README.md',
    [
      `# ${input.name}`,
      '',
      input.tagline ?? '',
      '',
      '## Run locally',
      '',
      '```bash',
      'npm install',
      'npx expo start',
      '```',
      '',
      '## Submit to stores',
      '',
      'Use [EAS Submit](https://docs.expo.dev/submit/introduction/) once you have an Apple Developer + Google Play account.',
      '',
      '## How it works',
      '',
      'This is a thin native shell that loads your live Edge Zone app in a WebView.',
      'Edit your screens in the dashboard — they update instantly, no rebuild needed.',
      '',
      '## Files of note',
      '',
      '- `App.js` — loads your live app (the WebView shell)',
      '- `src/config.js` — your app id + Edge Zone URL',
      '- `src/screens/*` — optional native-screen scaffold (not used by default)',
      '- `app.json` — bundle ids, version, icons',
      '- `package.json` — Expo + RN versions',
      '',
      'Generated by Edge Zone.',
    ].join('\n')
  )

  // ── Privacy policy template ──────────────────────────────────────
  zip.file('PRIVACY_POLICY.md', renderPrivacyPolicy(input))

  // ── Placeholder assets ───────────────────────────────────────────
  const assetsFolder = zip.folder('assets')!
  // Simple SVG icon + splash — dev replaces with real assets before submission.
  const iconSvg = renderIconSvg(input)
  assetsFolder.file('icon.svg', iconSvg)
  assetsFolder.file('splash.svg', iconSvg)
  assetsFolder.file('adaptive-icon.svg', iconSvg)
  assetsFolder.file(
    'README.txt',
    'Replace icon.png / splash.png / adaptive-icon.png with PNG versions of the SVGs in this folder (1024x1024 for icon, 2048x2048 for splash).'
  )

  const zipBuffer = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' })
  return { zipBuffer, filename: `${safeSlug}-expo.zip` }
}

function pascal(s: string): string {
  return s
    .replace(/[^a-z0-9]+/gi, ' ')
    .trim()
    .split(' ')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('')
}

function renderAppJs(input: ExpoBuildInput): string {
  const pushImport = input.push_enabled
    ? `import { useEffect } from 'react'\nimport { registerForPushNotifications } from './src/push'\n`
    : ''
  const pushHook = input.push_enabled
    ? `  useEffect(() => { registerForPushNotifications().catch(() => {}) }, [])\n`
    : ''
  const statusStyle = input.theme_mode === 'dark' ? 'light' : 'dark'
  return `import { StatusBar } from 'expo-status-bar'
import { SafeAreaProvider, SafeAreaView } from 'react-native-safe-area-context'
import { WebView } from 'react-native-webview'
${pushImport}import { EDGEZONE_API_URL, EDGEZONE_APP_ID } from './src/config'

// Your app loads live from Edge Zone — edit it in the dashboard and changes
// appear instantly, no rebuild required.
const APP_URL = EDGEZONE_API_URL + '/a/' + EDGEZONE_APP_ID

export default function App() {
${pushHook}  return (
    <SafeAreaProvider>
      <SafeAreaView style={{ flex: 1, backgroundColor: '${input.secondary_color}' }} edges={['top']}>
        <StatusBar style="${statusStyle}" />
        <WebView
          source={{ uri: APP_URL }}
          style={{ flex: 1, backgroundColor: '${input.secondary_color}' }}
          originWhitelist={['*']}
          startInLoadingState
          allowsInlineMediaPlayback
        />
      </SafeAreaView>
    </SafeAreaProvider>
  )
}
`
}

function renderPushModule(): string {
  return `import * as Notifications from 'expo-notifications'
import * as Device from 'expo-device'
import Constants from 'expo-constants'
import { Platform } from 'react-native'
import { EDGEZONE_APP_ID, EDGEZONE_API_URL } from './config'

Notifications.setNotificationHandler({
  handleNotification: async () => ({
    shouldShowAlert: true,
    shouldPlaySound: true,
    shouldSetBadge: true,
  }),
})

export async function registerForPushNotifications() {
  if (!Device.isDevice) return null
  const { status: existing } = await Notifications.getPermissionsAsync()
  let granted = existing
  if (existing !== 'granted') {
    const { status } = await Notifications.requestPermissionsAsync()
    granted = status
  }
  if (granted !== 'granted') return null

  const projectId = Constants?.expoConfig?.extra?.eas?.projectId ?? Constants?.easConfig?.projectId
  const { data: token } = await Notifications.getExpoPushTokenAsync(projectId ? { projectId } : undefined)
  if (!token) return null

  if (Platform.OS === 'android') {
    await Notifications.setNotificationChannelAsync('default', {
      name: 'default',
      importance: Notifications.AndroidImportance.MAX,
    })
  }

  try {
    await fetch(EDGEZONE_API_URL + '/api/apps/' + EDGEZONE_APP_ID + '/push/register', {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({
        token,
        platform: Platform.OS,
        deviceLabel: Device.modelName,
        appVersion: Constants?.expoConfig?.version,
      }),
    })
  } catch (e) {
    // Best-effort registration; user may be offline.
  }
  return token
}
`
}

function renderIapModule(): string {
  return `import { Platform } from 'react-native'
import { IAP_PRODUCTS } from './config'

// react-native-iap is loaded lazily so the JS bundle is fine in Expo Go,
// which doesn't ship the native module.
let IAP = null
async function ensureIAP() {
  if (IAP) return IAP
  try {
    IAP = await import('react-native-iap')
    return IAP
  } catch (e) {
    return null
  }
}

export async function initIAP() {
  const mod = await ensureIAP()
  if (!mod) return false
  await mod.initConnection()
  return true
}

export function listProducts() {
  return IAP_PRODUCTS
}

export function nativeProductIdsFor(platform = Platform.OS) {
  return IAP_PRODUCTS.map((p) => (platform === 'ios' ? p.apple_product_id : p.google_product_id)).filter(Boolean)
}

export async function purchase(productId) {
  const mod = await ensureIAP()
  if (!mod) throw new Error('IAP unavailable in this build')
  const nativeId =
    Platform.OS === 'ios'
      ? IAP_PRODUCTS.find((p) => p.product_id === productId)?.apple_product_id
      : IAP_PRODUCTS.find((p) => p.product_id === productId)?.google_product_id
  if (!nativeId) throw new Error('No native product ID configured for ' + productId)
  return mod.requestPurchase({ sku: nativeId })
}

export async function endIAP() {
  const mod = await ensureIAP()
  if (!mod) return
  await mod.endConnection()
}
`
}

function renderScreenJs(
  screen: ExpoBuildInput['screens'][number],
  input: ExpoBuildInput
): string {
  const componentName = pascal(screen.id) + 'Screen'
  const pattern: ScreenPattern = screenPattern(screen.type)
  const dataLiteral = JSON.stringify(screen.content ?? {})
  const fg = input.theme_mode === 'dark' ? '#ffffff' : '#0a0a0a'
  const sub = input.theme_mode === 'dark' ? 'rgba(255,255,255,0.6)' : 'rgba(0,0,0,0.55)'
  const bg = input.secondary_color
  const accent = input.primary_color
  const title = escapeJsString(screen.title)

  // Embedded web view — fills the screen, no scroll wrapper.
  if (pattern === 'web') {
    return `import { View, Text, StyleSheet } from 'react-native'
import { WebView } from 'react-native-webview'

const data = ${dataLiteral}

export default function ${componentName}() {
  if (!data.url) {
    return (
      <View style={styles.empty}>
        <Text style={styles.emptyText}>This page isn't configured yet.</Text>
      </View>
    )
  }
  return <WebView source={{ uri: data.url }} style={{ flex: 1, backgroundColor: '${bg}' }} />
}

const styles = StyleSheet.create({
  empty: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '${bg}' },
  emptyText: { color: '${sub}', fontSize: 15 },
})
`
  }

  const bodies: Record<Exclude<ScreenPattern, 'web'>, string> = {
    profile: `      {data.image ? <Image source={{ uri: data.image }} style={styles.hero} /> : null}
      <Text style={styles.h1}>{data.headline || '${title}'}</Text>
      {data.bio ? <Text style={styles.body}>{data.bio}</Text> : null}`,
    text: `      <Text style={styles.h1}>${title}</Text>
      <Text style={styles.body}>{data.body || ''}</Text>`,
    links: `      <Text style={styles.h1}>${title}</Text>
      {(data.items || []).filter(i => i && (i.label || i.url)).map((it, i) => (
        <Pressable key={i} style={styles.link} onPress={() => it.url && Linking.openURL(it.url)}>
          <Text style={styles.linkText}>{it.label || it.url}</Text>
          <Ionicons name="chevron-forward" size={18} color="${sub}" />
        </Pressable>
      ))}`,
    list: `      <Text style={styles.h1}>${title}</Text>
      {(data.items || []).filter(i => i && (i.title || i.subtitle || i.detail)).map((it, i) => (
        <View key={i} style={styles.card}>
          {it.title ? <Text style={styles.cardTitle}>{it.title}</Text> : null}
          {it.subtitle ? <Text style={styles.cardSub}>{it.subtitle}</Text> : null}
          {it.detail ? <Text style={styles.body}>{it.detail}</Text> : null}
        </View>
      ))}`,
    gallery: `      <Text style={styles.h1}>${title}</Text>
      <View style={styles.grid}>
        {(data.images || []).filter(Boolean).map((u, i) => (
          <Image key={i} source={{ uri: u }} style={styles.gridImg} />
        ))}
      </View>`,
    video: `      <Text style={styles.h1}>${title}</Text>
      {(data.items || []).filter(i => i && i.url).map((it, i) => (
        <Pressable key={i} style={styles.card} onPress={() => Linking.openURL(it.url)}>
          <Ionicons name="play-circle" size={28} color="${accent}" />
          <Text style={styles.cardTitle}>{it.title || 'Watch'}</Text>
        </Pressable>
      ))}`,
  }

  const needsLinking = pattern === 'links' || pattern === 'video'
  const needsImage = pattern === 'profile' || pattern === 'gallery'
  const rnImports = [
    'View',
    'Text',
    'ScrollView',
    'StyleSheet',
    ...(needsImage ? ['Image'] : []),
    ...(needsLinking ? ['Pressable', 'Linking'] : []),
  ].join(', ')
  const iconImport =
    needsLinking ? `\nimport { Ionicons } from '@expo/vector-icons'` : ''

  return `import { ${rnImports} } from 'react-native'${iconImport}

const data = ${dataLiteral}

export default function ${componentName}() {
  return (
    <ScrollView style={styles.container} contentContainerStyle={{ padding: 20 }}>
${bodies[pattern]}
    </ScrollView>
  )
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '${bg}' },
  hero: { width: '100%', height: 200, borderRadius: 14, marginBottom: 16 },
  h1: { fontSize: 28, fontWeight: '900', color: '${accent}', marginBottom: 14 },
  body: { color: '${fg}', fontSize: 15, lineHeight: 23 },
  link: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 14, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '${sub}' },
  linkText: { color: '${fg}', fontSize: 16, fontWeight: '600' },
  card: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: 'rgba(127,127,127,0.12)', borderRadius: 12, padding: 14, marginBottom: 10 },
  cardTitle: { color: '${fg}', fontSize: 16, fontWeight: '700' },
  cardSub: { color: '${sub}', fontSize: 13, marginTop: 2 },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  gridImg: { width: '31.5%', aspectRatio: 1, borderRadius: 8 },
})
`
}

function escapeJsString(s: string): string {
  return s.replace(/[\\'"]/g, '\\$&')
}

function renderPrivacyPolicy(input: ExpoBuildInput): string {
  const contact = input.contact_email ?? 'hello@theedgezone.com'
  return `# Privacy Policy

**App:** ${input.name}
**Effective:** ${new Date().toISOString().slice(0, 10)}

This app collects limited information needed to provide its features:

- **Identifiers**: Email address (if provided).
- **Usage data**: Crash reports and basic analytics that the platform (Expo) collects.

The app does not sell personal data. For data deletion or questions, email **${contact}**.

By using ${input.name}, you agree to this policy.

— Generated by Edge Zone.
`
}

function renderIconSvg(input: ExpoBuildInput): string {
  const initial = input.name.charAt(0).toUpperCase() || 'A'
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024">
  <rect width="1024" height="1024" fill="${input.secondary_color}" />
  <circle cx="512" cy="512" r="380" fill="${input.primary_color}" />
  <text x="512" y="640" font-family="Arial, sans-serif" font-size="540" font-weight="900" text-anchor="middle" fill="${input.secondary_color}">${initial}</text>
</svg>
`
}
