/**
 * Generates a per-app Expo (React Native) project ZIP.
 *
 * The output is a minimal but real Expo template the talent (or their
 * dev) can `npx expo install` against and ship. Everything dynamic
 * (app name, package id, screens, theme colors) is templated in from
 * the talent_apps row.
 */
import JSZip from 'jszip'

export interface ExpoBuildInput {
  name: string
  slug: string
  tagline?: string | null
  description?: string | null
  package_id: string
  primary_color: string
  secondary_color: string
  theme_mode: 'dark' | 'light'
  icon_url?: string | null
  splash_url?: string | null
  privacy_policy_url?: string | null
  contact_email?: string | null
  screens: Array<{
    id: string
    title: string
    icon?: string
    type: string
    content?: Record<string, unknown>
  }>
}

export async function buildExpoZip(
  input: ExpoBuildInput
): Promise<{ zipBuffer: Buffer; filename: string }> {
  const zip = new JSZip()
  const safeSlug = input.slug.replace(/[^a-z0-9-]/gi, '-')

  // ── package.json ──────────────────────────────────────────────────
  zip.file(
    'package.json',
    JSON.stringify(
      {
        name: safeSlug,
        version: '1.0.0',
        main: 'index.js',
        scripts: {
          start: 'expo start',
          android: 'expo run:android',
          ios: 'expo run:ios',
        },
        dependencies: {
          expo: '~51.0.0',
          'expo-status-bar': '~1.12.0',
          react: '18.2.0',
          'react-native': '0.74.5',
          '@react-navigation/native': '^6.1.18',
          '@react-navigation/bottom-tabs': '^6.6.0',
          '@expo/vector-icons': '^14.0.0',
          'react-native-safe-area-context': '4.10.5',
          'react-native-screens': '3.31.1',
        },
      },
      null,
      2
    )
  )

  // ── app.json ──────────────────────────────────────────────────────
  zip.file(
    'app.json',
    JSON.stringify(
      {
        expo: {
          name: input.name,
          slug: safeSlug,
          version: '1.0.0',
          orientation: 'portrait',
          icon: input.icon_url ? './assets/icon.png' : './assets/icon.png',
          userInterfaceStyle: input.theme_mode === 'dark' ? 'dark' : 'light',
          splash: {
            image: './assets/splash.png',
            resizeMode: 'contain',
            backgroundColor: input.secondary_color,
          },
          assetBundlePatterns: ['**/*'],
          ios: {
            supportsTablet: true,
            bundleIdentifier: input.package_id,
            buildNumber: '1',
          },
          android: {
            package: input.package_id,
            versionCode: 1,
            adaptiveIcon: {
              foregroundImage: './assets/adaptive-icon.png',
              backgroundColor: input.primary_color,
            },
          },
          web: { favicon: './assets/icon.png' },
        },
      },
      null,
      2
    )
  )

  // ── babel.config.js ────────────────────────────────────────────────
  zip.file(
    'babel.config.js',
    `module.exports = function (api) {
  api.cache(true)
  return {
    presets: ['babel-preset-expo'],
  }
}
`
  )

  // ── index.js ──────────────────────────────────────────────────────
  zip.file('index.js', `import { registerRootComponent } from 'expo'\nimport App from './App'\nregisterRootComponent(App)\n`)

  // ── App.js (entry) ────────────────────────────────────────────────
  zip.file(
    'App.js',
    renderAppJs(input)
  )

  // ── Screens ──────────────────────────────────────────────────────
  const srcFolder = zip.folder('src')!
  const screensFolder = srcFolder.folder('screens')!
  for (const screen of input.screens) {
    screensFolder.file(`${pascal(screen.id)}Screen.js`, renderScreenJs(screen, input))
  }

  // ── README ───────────────────────────────────────────────────────
  zip.file(
    'README.md',
    [
      `# ${input.name}`,
      '',
      input.tagline ?? '',
      '',
      '## Run locally',
      '',
      '```bash',
      'npm install',
      'npx expo start',
      '```',
      '',
      '## Submit to stores',
      '',
      'Use [EAS Submit](https://docs.expo.dev/submit/introduction/) once you have an Apple Developer + Google Play account.',
      '',
      '## Files of note',
      '',
      '- `App.js` — root navigator',
      '- `src/screens/*` — individual screens',
      '- `app.json` — bundle ids, version, icons',
      '- `package.json` — Expo + RN versions',
      '',
      'Generated by Edge Zone.',
    ].join('\n')
  )

  // ── Privacy policy template ──────────────────────────────────────
  zip.file('PRIVACY_POLICY.md', renderPrivacyPolicy(input))

  // ── Placeholder assets ───────────────────────────────────────────
  const assetsFolder = zip.folder('assets')!
  // Simple SVG icon + splash — dev replaces with real assets before submission.
  const iconSvg = renderIconSvg(input)
  assetsFolder.file('icon.svg', iconSvg)
  assetsFolder.file('splash.svg', iconSvg)
  assetsFolder.file('adaptive-icon.svg', iconSvg)
  assetsFolder.file(
    'README.txt',
    'Replace icon.png / splash.png / adaptive-icon.png with PNG versions of the SVGs in this folder (1024x1024 for icon, 2048x2048 for splash).'
  )

  const zipBuffer = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' })
  return { zipBuffer, filename: `${safeSlug}-expo.zip` }
}

function pascal(s: string): string {
  return s
    .replace(/[^a-z0-9]+/gi, ' ')
    .trim()
    .split(' ')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('')
}

function renderAppJs(input: ExpoBuildInput): string {
  const tabs = input.screens
    .map((s) => {
      const component = pascal(s.id) + 'Screen'
      return `        <Tab.Screen name="${s.title}" component={${component}} />`
    })
    .join('\n')
  const imports = input.screens
    .map((s) => `import ${pascal(s.id)}Screen from './src/screens/${pascal(s.id)}Screen'`)
    .join('\n')

  return `import 'react-native-gesture-handler'
import { NavigationContainer, DefaultTheme, DarkTheme } from '@react-navigation/native'
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs'
${imports}

const Tab = createBottomTabNavigator()

const theme = {
  ...(${input.theme_mode === 'dark' ? 'DarkTheme' : 'DefaultTheme'}),
  colors: {
    ...(${input.theme_mode === 'dark' ? 'DarkTheme' : 'DefaultTheme'}.colors),
    primary: '${input.primary_color}',
    background: '${input.secondary_color}',
  },
}

export default function App() {
  return (
    <NavigationContainer theme={theme}>
      <Tab.Navigator screenOptions={{ headerShown: false, tabBarActiveTintColor: '${input.primary_color}' }}>
${tabs}
      </Tab.Navigator>
    </NavigationContainer>
  )
}
`
}

function renderScreenJs(
  screen: ExpoBuildInput['screens'][number],
  input: ExpoBuildInput
): string {
  const safeContent = JSON.stringify(screen.content ?? {}, null, 2)
  const componentName = pascal(screen.id) + 'Screen'
  return `import { View, Text, ScrollView, StyleSheet } from 'react-native'

const data = ${safeContent}

export default function ${componentName}() {
  return (
    <ScrollView style={styles.container} contentContainerStyle={{ padding: 20 }}>
      <Text style={styles.title}>${escapeJsString(screen.title)}</Text>
      <Text style={styles.body}>{JSON.stringify(data, null, 2)}</Text>
    </ScrollView>
  )
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '${input.secondary_color}',
  },
  title: {
    fontSize: 28,
    fontWeight: '900',
    color: '${input.primary_color}',
    marginBottom: 16,
  },
  body: {
    color: '${input.theme_mode === 'dark' ? '#fff' : '#000'}',
    fontSize: 14,
    lineHeight: 22,
    fontFamily: 'Menlo',
  },
})
`
}

function escapeJsString(s: string): string {
  return s.replace(/[\\'"]/g, '\\$&')
}

function renderPrivacyPolicy(input: ExpoBuildInput): string {
  const contact = input.contact_email ?? 'hello@theedgezone.com'
  return `# Privacy Policy

**App:** ${input.name}
**Effective:** ${new Date().toISOString().slice(0, 10)}

This app collects limited information needed to provide its features:

- **Identifiers**: Email address (if provided).
- **Usage data**: Crash reports and basic analytics that the platform (Expo) collects.

The app does not sell personal data. For data deletion or questions, email **${contact}**.

By using ${input.name}, you agree to this policy.

— Generated by Edge Zone.
`
}

function renderIconSvg(input: ExpoBuildInput): string {
  const initial = input.name.charAt(0).toUpperCase() || 'A'
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024">
  <rect width="1024" height="1024" fill="${input.secondary_color}" />
  <circle cx="512" cy="512" r="380" fill="${input.primary_color}" />
  <text x="512" y="640" font-family="Arial, sans-serif" font-size="540" font-weight="900" text-anchor="middle" fill="${input.secondary_color}">${initial}</text>
</svg>
`
}
